### PR TITLE
Enable websockets on the live view

### PR DESCRIPTION
**Pull request by mosic**
This needs to be deployed after websocket support is enabled in `evercam-media`.

### CODE REVIEW

**Comment by marcoherbst** [comment]
@mosic  ... why is this still here? Can it go? or can you make a note to tell us to keep it.

**Comment by mosic** [comment]
@marcoherbst This is waiting for a change in evercam-media which still needs to be done.

**Comment by marcoherbst** [comment]
@mosic  is this still live and relevant?

**Comment by mosic** [comment]
@marcoherbst No, this has been superseded by https://github.com/evercam/evercam-dashboard/pull/871, thanks for noticing. Closing.

**Pull request closed without merging**
