### PR TITLE
Add Evercam Media API endpoint config

### PR DESCRIPTION
**Pull request by fteem**

### CODE REVIEW

**Comment by fteem** [comment]
This PR required dashboards' ```.env``` file to include:
```
EVERCAM_MEDIA_API=http://localhost:4000
```

**Comment by mosic** [comment]
Looks good but we should also set the default for `EVERCAM_MEDIA_API` in production, same way we do for `EVERCAM_API`.

Also a reminder, you need to sign the CLA: https://www.clahub.com/agreements/evercam/evercam-api

**Comment by fteem** [comment]
@mosic I've updated the constants, lemme know if something needs fixing.

**Comment by mosic** [comment]
:shipit:

**Pull request merged**
