### PR TITLE
New info widget

### PR DESCRIPTION
**Pull request by muneeb2542**
@azharmalik3

### CODE REVIEW

**Comment by muneeb2542** [comment]
@mosic I have made a new info widget for the details page.It is still not finished,a lot of the CSS work is left and a little changes are left in the main HTML file.

So please instruct me how to proceed with this further.

**Comment by mosic** [comment]
@muneeb2542 Can you be a little more specific, what are you having problems with?

**Comment by muneeb2542** [comment]
@mosic There is not a problem with it instead, I wanted you to see if this procedure for making a new details widget be okay?

**Comment by mosic** [comment]
@muneeb2542 It does seem okay, but some cleanup is needed. For example, the javascript file includes the libraries for the full screen, calendar etc. which are all unnecessary.

**Comment by muneeb2542** [comment]
@mosic yes i see that,i intend to remove those files and do a clean up on it.

**Pull request closed without merging**
