### PR TITLE
change live snapshot to pull data from media api

### PR DESCRIPTION
**Pull request by fteem**
@mosic check this out.

### CODE REVIEW

**Comment by mosic** [comment]
Looks good, but have you tried making the request with and without `.jpg` extension? Does the current evercam-media implementation support both?

**Comment by fteem** [comment]
@mosic is there a easy way (TM) to test that out?

**Comment by mosic** [comment]
Well regular curl request or opening both versions in the browser should be fine. For reference, the old implementation supports both 

```
https://api.evercam.io/v1/cameras/austin/live/snapshot
```

and 

```
https://api.evercam.io/v1/cameras/austin/live/snapshot.jpg
```

**Comment by marcoherbst** [comment]
@mosic ... is this still live and relevant ?

**Comment by mosic** [comment]
@marcoherbst Somewhat, this depends on the Auth code, which should get merged in the next couple of days.

**Comment by mosic** [comment]
Done in https://github.com/evercam/evercam-dashboard/commit/8f2e7df2ad8a6deaf45e807534e43fa89f3e8c3d.

**Pull request closed without merging**
